In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import StandardScaler # Used for scaling of data
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import metrics
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
from keras import backend as K
from keras.wrappers.scikit_learn import KerasRegressor

In [4]:
data = pd.read_csv('train.csv', index_col=0)
type(data)
data

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [ ]:
corrmat =data.corr()
corrmat
cols = corrmat.nlargest(20, 'SalePrice')['SalePrice'].index

In [ ]:
top18cols=cols[1:19]
top18=list(top18cols)
all19=top18.copy()
all19.append('SalePrice')
top5classCols=list(top18cols[[0,2,6,7,12]])
#top18,top18cols,all19,top5classCols

In [5]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df_train.drop("Id", axis = 1, inplace = True)
df_test.drop("Id", axis = 1, inplace = True)
#df_train

In [6]:
df_train = df_train.drop(df_train[(df_train['GrLivArea']>4000) & (df_train['SalePrice']<300000)].index)

In [7]:
df_train['SalePrice'] = np.log(df_train['SalePrice']+1)

In [8]:
ntrain = df_train.shape[0]
ntest = df_test.shape[0]
print(ntest,ntrain)
y_train = df_train.SalePrice.values
comp_data = pd.concat((df_train,df_test)).reset_index(drop=True)
comp_data.drop(['SalePrice'], axis=1, inplace=True)
print("Comp_data size is : {}".format(comp_data.shape))
comp_data

1459 1458
Comp_data size is : (2917, 79)

C:\Users\User\Anaconda3\envs\tens\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """

,1stFlrSF,2ndFlrSF,3SsnPorch,Alley,BedroomAbvGr,BldgType,BsmtCond,BsmtExposure,BsmtFinSF1,BsmtFinSF2,...,SaleType,ScreenPorch,Street,TotRmsAbvGrd,TotalBsmtSF,Utilities,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,856,854,0,NaN,3,1Fam,TA,No,706.0,0.0,...,WD,0,Pave,8,856.0,AllPub,0,2003,2003,2008
1,1262,0,0,NaN,3,1Fam,TA,Gd,978.0,0.0,...,WD,0,Pave,6,1262.0,AllPub,298,1976,1976,2007
2,920,866,0,NaN,3,1Fam,TA,Mn,486.0,0.0,...,WD,0,Pave,6,920.0,AllPub,0,2001,2002,2008
3,961,756,0,NaN,3,1Fam,Gd,No,216.0,0.0,...,WD,0,Pave,7,756.0,AllPub,0,1915,1970,2006
4,1145,1053,0,NaN,4,1Fam,TA,Av,655.0,0.0,...,WD,0,Pave,9,1145.0,AllPub,192,2000,2000,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2912,546,546,0,NaN,3,Twnhs,TA,No,0.0,0.0,...,WD,0,Pave,5,546.0,AllPub,0,1970,1970,2006
2913,546,546,0,NaN,3,TwnhsE,TA,No,252.0,0.0,...,WD,0,Pave,6,546.0,AllPub,0,1970,1970,2006
2914,1224,0,0,NaN,4,1Fam,TA,No,1224.0,0.0,...,WD,0,Pave,7,1224.0,AllPub,474,1960,1996,2006
2915,970,0,0,NaN,3,1Fam,TA,Av,337.0,0.0,...,WD,0,Pave,6,912.0,AllPub,80,1992,1992,2006
2916,996,1004,0,NaN,3,1Fam,TA,Av,758.0,0.0,...,WD,0,Pave,9,996.0,AllPub,190,1993,1994,2006

In [9]:
comp_data["LotFrontage"] = comp_data.groupby("Neighborhood")["LotFrontage"].transform(
    lambda x: x.fillna(x.median()))
for col in ('GarageYrBlt', 'GarageArea', 'GarageCars'):
    comp_data[col] = comp_data[col].fillna(0)
for col in ('BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF','TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath'):
    comp_data[col] = comp_data[col].fillna(0)
comp_data['MSZoning'] = comp_data['MSZoning'].fillna(comp_data['MSZoning'].mode()[0])
comp_data["MasVnrArea"] = comp_data["MasVnrArea"].fillna(0)
comp_data['Electrical'] = comp_data['Electrical'].fillna(comp_data['Electrical'].mode()[0])
comp_data['SaleType'] = comp_data['SaleType'].fillna(comp_data['SaleType'].mode()[0])
comp_data['KitchenQual'] = comp_data['KitchenQual'].fillna(comp_data['KitchenQual'].mode()[0])
comp_data['Exterior1st'] = comp_data['Exterior1st'].fillna(comp_data['Exterior1st'].mode()[0])
comp_data['Exterior2nd'] = comp_data['Exterior2nd'].fillna(comp_data['Exterior2nd'].mode()[0])

In [10]:
for col in ('PoolQC', 'MiscFeature', 'Alley'):
    comp_data[col] = comp_data[col].fillna('None')
comp_data["MasVnrType"] = comp_data["MasVnrType"].fillna("None")
comp_data["Fence"] = comp_data["Fence"].fillna("None")
comp_data["FireplaceQu"] = comp_data["FireplaceQu"].fillna("None")
for col in ('GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'):
    comp_data[col] = comp_data[col].fillna('None')
for col in ('BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2'):
    comp_data[col] = comp_data[col].fillna('None')
comp_data['MSSubClass'] = comp_data['MSSubClass'].fillna("None")
comp_data['SaleType'] = comp_data['SaleType'].fillna(comp_data['SaleType'].mode()[0])
comp_data = comp_data.drop(['Utilities'], axis=1)
comp_data['OverallCond'] = comp_data['OverallCond'].astype(str)
comp_data["Functional"] = comp_data["Functional"].fillna("Typ")

In [11]:
comp_data['MSSubClass'] = comp_data['MSSubClass'].apply(str)
comp_data['YrSold'] = comp_data['YrSold'].astype(str)
comp_data['MoSold'] = comp_data['MoSold'].astype(str)
from sklearn.preprocessing import LabelEncoder
columns = ('FireplaceQu', 'BsmtQual', 'BsmtCond', 'GarageQual', 'GarageCond', 
        'ExterQual', 'ExterCond','HeatingQC', 'PoolQC', 'KitchenQual', 'BsmtFinType1', 
        'BsmtFinType2', 'Functional', 'Fence', 'BsmtExposure', 'GarageFinish', 'LandSlope',
        'LotShape', 'PavedDrive', 'Street', 'Alley', 'CentralAir', 'MSSubClass', 'OverallCond', 
        'YrSold', 'MoSold')
for col in columns:
    labl = LabelEncoder() 
    labl.fit(list(comp_data[col].values)) 
    comp_data[col] = labl.transform(list(comp_data[col].values))     
print('Shape all_data: {}'.format(comp_data.shape))
comp_data['TotalSF'] = comp_data['TotalBsmtSF'] + comp_data['1stFlrSF'] + comp_data['2ndFlrSF']

Shape all_data: (2917, 78)

In [ ]:
from scipy.stats import norm, skew
numeric_feats = comp_data.dtypes[comp_data.dtypes != "object"].index

# Check the skew of all numerical features
skewed_feats = comp_data[numeric_feats].apply(lambda x: skew(x.dropna())).sort_values(ascending=False)
print("\nSkew in numerical features: \n")
skewness = pd.DataFrame({'Skew' :skewed_feats})

In [ ]:
skewness = skewness[abs(skewness) > 0.75]
print("There are {} skewed numerical features to Box Cox transform".format(skewness.shape[0]))

from scipy.special import boxcox1p
skewed_features = skewness.index
lam = 0.15
for feat in skewed_features:
    comp_data[feat] = boxcox1p(comp_data[feat], lam)

In [ ]:
print(comp_data.shape)
kk=comp_data
#print(kk)
#comp_data=comp_data[top18]
#print(comp_data)

In [12]:
comp_data = pd.get_dummies(comp_data)
print(comp_data.shape)

(2917, 220)

In [13]:
train_df = comp_data[:ntrain]
test_df = comp_data[ntrain:]
train_df.shape,test_df.shape

((1458, 220), (1459, 220))

In [26]:
test_df

,1stFlrSF,2ndFlrSF,3SsnPorch,Alley,BedroomAbvGr,BsmtCond,BsmtExposure,BsmtFinSF1,BsmtFinSF2,BsmtFinType1,...,SaleCondition_Partial,SaleType_COD,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD
1458,896,0,0,1,2,4,3,468.0,144.0,5,...,0,0,0,0,0,0,0,0,0,1
1459,1329,0,0,1,3,4,3,923.0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
1460,928,701,0,1,3,4,3,791.0,0.0,2,...,0,0,0,0,0,0,0,0,0,1
1461,926,678,0,1,3,4,3,602.0,0.0,2,...,0,0,0,0,0,0,0,0,0,1
1462,1280,0,0,1,2,4,3,263.0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2912,546,546,0,1,3,4,3,0.0,0.0,6,...,0,0,0,0,0,0,0,0,0,1
2913,546,546,0,1,3,4,3,252.0,0.0,5,...,0,0,0,0,0,0,0,0,0,1
2914,1224,0,0,1,4,4,3,1224.0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
2915,970,0,0,1,3,4,0,337.0,0.0,2,...,0,0,0,0,0,0,0,0,0,1
2916,996,1004,0,1,3,4,0,758.0,0.0,3,...,0,0,0,0,0,0,0,0,0,1

In [12]:
X_train, X_test, y_train, y_test = train_test_split(train_df, y_train, test_size=0.33, random_state=1)

In [13]:
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(512, input_dim=X_train.shape[1], activation='relu'))
    #model.add(Dropout(0.9))
    model.add(Dense(512, activation='relu'))
    #model.add(Dropout(0.9))
    #model.add(Dense(384, activation='relu'))
    
    model.add(Dense(1))
    # Compile model
    model.compile(optimizer ='adam', loss = 'mean_squared_error', 
              metrics =[metrics.mae])
    return model

In [ ]:
model = create_model()
model.summary()

In [ ]:
from keras.callbacks import ReduceLROnPlateau
reduce_lr = ReduceLROnPlateau(monitor='val_loss',patience=10,verbose=1,factor=0.2,min_lr=0.00001)
# Available metrics are: val_loss,val_mean_absolute_error,loss,mean_absolute_error,lr

In [14]:
model = create_model()
history = model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=10, batch_size=32)#,callbacks=[reduce_lr])
loss,acc = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test loss:', acc)

WARNING:tensorflow:From C:\Users\User\Anaconda3\envs\tens\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Train on 976 samples, validate on 482 samples
Epoch 1/10
976/976 [==============================] - 1s 577us/step - loss: 941259.6351 - mean_absolute_error: 621.5758 - val_loss: 309057.6718 - val_mean_absolute_error: 232.6449
Epoch 2/10
976/976 [==============================] - 0s 247us/step - loss: 233355.4014 - mean_absolute_error: 333.9233 - val_loss: 79372.3155 - val_mean_absolute_error: 103.0353
Epoch 3/10
976/976 [==============================] - 0s 248us/step - loss: 198285.0244 - mean_absolute_error: 338.2426 - val_loss: 2173.0004 - val_mean_absolute_error: 26.6454
Epoch 4/10
976/976 [==============================] - 0s 248us/step - loss: 108416.1841 - mean_absolute_error: 237.2869 - val_loss: 37774.2114 - val_mean_absolute_error: 55.8696
Epoch 5/10
976/976 [==============================] - 0s 246us/step - loss: 24310.0289 - mean_absolute_error: 70.1116 - val_loss: 66853.7015 - val_mean_absolute_error: 230.3682
Epoch 6/10
976/976 [==============================] - 0s 249us/step - loss: 42725.2112 - mean_absolute_error: 153.9013 - val_loss: 37458.9253 - val_mean_absolute_error: 167.9485
Epoch 7/10
976/976 [==============================] - 0s 246us/step - loss: 6053.6406 - mean_absolute_error: 47.3663 - val_loss: 1603.3417 - val_mean_absolute_error: 37.6751
Epoch 8/10
976/976 [==============================] - 0s 247us/step - loss: 1671.7960 - mean_absolute_error: 30.0820 - val_loss: 584.2733 - val_mean_absolute_error: 18.3784
Epoch 9/10
976/976 [==============================] - 0s 248us/step - loss: 473.7100 - mean_absolute_error: 14.6755 - val_loss: 221.9448 - val_mean_absolute_error: 7.6994
Epoch 10/10
976/976 [==============================] - 0s 248us/step - loss: 243.5667 - mean_absolute_error: 10.7153 - val_loss: 203.0404 - val_mean_absolute_error: 9.1175
Test loss: 203.04039805558708
Test loss: 9.117523193359375

In [ ]:
# summarize history for accuracy
plt.plot(history.history['mean_absolute_error'])
plt.plot(history.history['val_mean_absolute_error'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
# summarize history for loss

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
loss,acc = model.evaluate(X_test, y_test, verbose=0)
    
print('Test loss:', loss)
print('Test loss:', acc)

In [1]:
#model.save('mykaggle_model.h5') 
#del model
from keras.models import load_model
model = load_model('mykaggle_model.h5')

Using TensorFlow backend.

WARNING:tensorflow:From C:\Users\User\Anaconda3\envs\tens\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

In [ ]:
for key in history.history :
    print(key)

In [ ]:
'''
val_mean_absolute_error
Test loss: 0.02877828227626585
Test loss: 0.11960650980472565
Test loss: 0.029834422893451208
Test loss: 0.12421250343322754
Test loss: 0.02931691233563349
Test loss: 0.11997009813785553
mean_absolute_error
Test loss: 0.028362277947381696
Test loss: 0.12079749256372452
Test loss: 0.027598328428551616
Test loss: 0.12202514708042145
Test loss: 0.027732883174266063
Test loss: 0.11755037307739258
loss
Test loss: 0.027609399090911344
Test loss: 0.1173456460237503
Test loss: 0.027434247294711375
Test loss: 0.1206061914563179
Test loss: 0.029334306643495175
Test loss: 0.12025696784257889
val_loss
Test loss: 0.027879059388151554
Test loss: 0.1201024204492569
Test loss: 0.027348946470813634
Test loss: 0.11799003183841705
Test loss: 0.0295340278846718
Test loss: 0.1222539097070694
'''

In [ ]:
#df_test = pd.read_csv('test.csv')

In [ ]:
#cols = ['OverallQual', 'GrLivArea', 'GarageCars', 'FullBath', 'YearBuilt']
#cols=['OverallQual', 'GrLivArea', 'GarageCars','TotalBsmtSF', 'FullBath', 'TotRmsAbvGrd']
id_col = pd.read_csv('test.csv')['Id'].values.tolist()
#df_test['GrLivArea'] = np.log1p(df_test['GrLivArea'])
#df_test = pd.get_dummies(df_test)
#df_test = df_test.fillna(df_test.mean())
#x_test = df_test[top18].values
# Always standard scale the data before using NN
#x_test= StandardScaler().fit_transform(x_test)

In [14]:
prediction = model.predict(train_df.head())

InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(5, 220), b.shape=(220, 512), m=5, n=512, k=220
	 [[{{node dense_4/MatMul}}]]
  (1) Internal: Blas GEMM launch failed : a.shape=(5, 220), b.shape=(220, 512), m=5, n=512, k=220
	 [[{{node dense_4/MatMul}}]]
	 [[dense_6/BiasAdd/_203]]
0 successful operations.
0 derived errors ignored.

In [16]:
prediction

array([[16.611717],
       [20.997515],
       [21.81551 ],
       [12.702768],
       [15.24539 ]], dtype=float32)

In [ ]:
submission = pd.DataFrame()
submission['Id'] = id_col
submission['SalePrice'] = np.expm1(prediction)

In [ ]:
submission.to_csv('keras_submission_astype_allcol.csv', index=False)

In [ ]:
#revision=pd.read_csv('keras_submission_astype1.csv')
#revision

In [ ]:
submission = pd.DataFrame()
submission['Id'] = id_col
submission['SalePrice'] = np.expm1(revision['SalePrice'])
submission.to_csv('keras_submission_astype1.csv', index=False)

In [ ]:
import pandas as pd
from io import StringIO
 
csv_data = '''A,B,C,D
1,2,3,4
5,6,,8
0,11,12,'''
 
df = pd.read_csv(StringIO(csv_data))
print(df)
#統計為空的數目
print(df.isnull().sum())
print(df.values)
 
#丟棄空的
print(df.dropna())
print('after', df)

In [ ]:
from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
color_le = LabelEncoder()
df['classlabel'] = class_le.fit_transform(df['classlabel'].values)
#df['color'] = color_le.fit_transform(df['color'].values)
print(df)

In [ ]:
from sklearn.preprocessing import Imputer
# axis=0 列  axis = 1 行
imr = Imputer(missing_values='NaN', strategy='mean', axis=0)
imr.fit(df) # fit 構建得到資料
imputed_data = imr.transform(df.values) #transform 將資料進行填充
print(imputed_data)
 
df = pd.DataFrame([['green', 'M', 10.1, 'class1'],
          ['red', 'L', 13.5, 'class2'],
          ['blue', 'XL', 15.3, 'class1']])
df.columns =['color', 'size', 'price', 'classlabel']
print(df)
 
size_mapping = {'XL':3, 'L':2, 'M':1}
df['size'] = df['size'].map(size_mapping)
print(df)
 ## 遍歷Series
for idx, label in enumerate(df['classlabel']):
  print(idx, label)

In [ ]:



 
#1, 利用LabelEncoder類快速編碼,但此時對color並不適合,
#看起來,好像是有大小的

#2, 對映字典將類標轉換為整數
import numpy as np
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}
df['classlabel'] = df['classlabel'].map(class_mapping)
print('2,', df)
 
 
#3,處理1不適用的
#利用建立一個新的虛擬特徵
from sklearn.preprocessing import OneHotEncoder
pf = pd.get_dummies(df[['color']])
df = pd.concat([df, pf], axis=1)
df.drop(['color'], axis=1, inplace=True)
print(df)